baseURL = "https://ru.alxschwarz.com/"
title = "0xC79D7A"

[indexes]
  tag = "tags"

[params]
  Author = "Alex Feller"
  #Subtitle = "Your site's subtitle/tagline"
  GithubID = "alexfinn"
  TwitterID = "alxschwarz"
  AnalyticsID = "5379d5ebe32bb402be001a01"
  DisqusShortname = "Your Disqus shortname"
  Summary = false  # takes true or false
  Content = false  # takes true or false
  # if both are set to true, summary is shown.
  FooterMsg = "©∆LX 2009-2019"

staticDir = ["static"]

[permalinks]
  post = "/:slug/"
